model_id: gpt-4o-mini
batch_size: 16
concurrency: 20
n: 1
temperature: 0.6
unique_key: "id"
save_key: "safety_label"
query_key: "Dialog_Response"
mode: "general"

input_dir: "round/2"

output_dir: "round/2/label"
output_file: null
base_url: null
